---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-db
  template:
    metadata:
      labels:
        app: music-db
    spec:
      containers:
        - name: music-db
          image: music-db:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: 'music'
            - name: MYSQL_USER
              value: 'music-user'
            - name: MYSQL_PASSWORD
              value: 'pass'
            - name: MYSQL_ROOT_PASSWORD
              value: 'password'
---
apiVersion: v1
kind: Service
metadata:
  name: music-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
      name: db
  selector:
    app: music-db
  type: NodePort