---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-listener
  template:
    metadata:
      labels:
        app: statistics-listener
    spec:
      containers:
      - name: statistics-listener
        image: statistics-listener:latest
        imagePullPolicy: Never
        env:
          - name: RABBIT_URL
            value: 'rabbit'
          - name: RABBIT_PORT
            value: '5672'
          - name: RABBIT_USER
            value: 'guest'
          - name: RABBIT_PASS
            value: 'guest'
          - name: DB_USER
            value: "statistics-user"
          - name: DB_PASS
            value: "pass"
          - name: DB_URL
            value: "statistics-db"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "statistics"
          - name: MUSIC_ADDRESS
            value: "music-service"
          - name: MUSIC_PORT
            value: "8080"
        

---
apiVersion: v1
kind: Service
metadata:
  name: statistics-service
spec:
  ports:
  - nodePort: 30085
    port: 8080
    targetPort: 8080
  selector:
    app: statistics-service
  type: NodePort
