---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-db
  template:
    metadata:
      labels:
        app: statistics-db
    spec:
      containers:
        - name: statistics-db
          image: statistics-db:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: 'statistics'
            - name: MYSQL_USER
              value: 'statistics-user'
            - name: MYSQL_PASSWORD
              value: 'pass'
            - name: MYSQL_ROOT_PASSWORD
              value: 'password'
---
apiVersion: v1
kind: Service
metadata:
  name: statistics-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30308
      name: db
  selector:
    app: statistics-db
  type: NodePort