---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: users-service:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        env:
        - name: DB_USER
          value: "users-user"
        - name: DB_PASS
          value: "pass"
        - name: DB_URL
          value: "users-db"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "users"

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  ports:
  - nodePort: 30083
    port: 8080
    targetPort: 8080
  selector:
    app: users-service
  type: NodePort
