---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - name: users-db
          image: users-db:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: 'users'
            - name: MYSQL_USER
              value: 'users-user'
            - name: MYSQL_PASSWORD
              value: 'pass'
            - name: MYSQL_ROOT_PASSWORD
              value: 'password'
---
apiVersion: v1
kind: Service
metadata:
  name: users-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodeport: 30307
      name: db
  selector:
    app: users-db
  type: NodePort